kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker/compose:latest
    commands:
      - docker-compose up --build -d
    volumes:
      - name: docker
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker
